### ISSUE TITLE
When used inside of gulp-if, prints count even if gulp-if condition is false

### ISSUE THREAD

**Issue by lucastheisen** [sindresorhus/gulp-debug#33] opened 2016-09-01 18:12 UTC
Specifically, i have a task that looks like this:
```
gulp.task('copy-bower-cesium-gulp-if', function() {
    var destination = buildDir('bower_libs');
    return gulp
        .src(
            [
                bowerDir('cesium', 'Cesium', '**', '*'),
                bowerDir('cesium', 'CesiumUnminified', '**', '*')
            ],
            {base: bowerDir()})
        .pipe(gulpIf(argv.debug, debug({title: 'copy-bower-cesium:'})))
        .pipe(gulp.dest(destination));
})
```
If i supply the command line arg (using yargs) `--debug`:
```
PS > .\node\node.exe .\node_modules\gulp\bin\gulp.js copy-bower-cesium-gulp-if --debug  
[14:15:34] Using gulpfile ~\project\gulpfile.js                                                                  
[14:15:34] Starting 'copy-bower-cesium-gulp-if'...                                                                                                          
[14:15:34] copy-bower-cesium: target\bower_libs\cesium\Cesium\Assets                                                                                        
[14:15:35] copy-bower-cesium: target\bower_libs\cesium\Cesium\Cesium.js                                                                                     
[14:15:35] copy-bower-cesium: target\bower_libs\cesium\Cesium\ThirdParty                                                                                    
...
[14:15:36] copy-bower-cesium: target\bower_libs\cesium\CesiumUnminified\Assets\Textures\NaturalEarthII\2\3\2.jpg
[14:15:36] copy-bower-cesium: target\bower_libs\cesium\CesiumUnminified\Assets\Textures\NaturalEarthII\2\3\3.jpg
[14:15:36] copy-bower-cesium: 658 items
[14:15:36] Finished 'copy-bower-cesium-gulp-if' after 1.81 s
```
Which is exactly what I want.  However, when I dont supply `--debug`, it shows _0 items_:
```
PS > .\node\node.exe .\node_modules\gulp\bin\gulp.js copy-bower-cesium-gulp-if
[14:15:45] Using gulpfile ~\project\gulpfile.js
[14:15:45] Starting 'copy-bower-cesium-gulp-if'...
[14:15:46] copy-bower-cesium: 0 items
[14:15:47] Finished 'copy-bower-cesium-gulp-if' after 1.51 s
```

**Comment by sindresorhus** [comment] 2016-09-02 07:12
Duplicate of https://github.com/sindresorhus/gulp-debug/issues/32.

**Closed by sindresorhus** 2016-09-02 07:12 UTC
